### ISSUE TITLE
Infinity loop when "U*" template

### ISSUE THREAD

**Issue by ksss** [iij/mruby-pack#12]
The following input results in an infinite loop.

```rb
"".unpack("U*")
```

`count` set `-1` in this line.
https://github.com/iij/mruby-pack/blob/88a7fedea413568a1ff0410e109ff55a03b63a5f/src/pack.c#L960

Then, `count != 0` never match.
https://github.com/iij/mruby-pack/blob/88a7fedea413568a1ff0410e109ff55a03b63a5f/src/pack.c#L1123

I expect like this

```
$ ruby -e 'p "".unpack("U*")'
[]

$ ruby -e 'p "あいうえお".unpack("U*")'
[12354, 12356, 12358, 12360, 12362]
```

**Comment by tsahara** [comment]
Fixed by https://github.com/iij/mruby-pack/pull/13.
